branch-defaults:
  master:
    environment: atlas-new-dev
global:
  application_name: atlas-new
  default_ec2_keyname: atlas
  default_platform: Node.js 4.2.1
  default_region: us-west-2
  profile: eb-cli
  sc: git